catalog/urls.py
from django.conf.urls import url

from catalog import views


urlpatterns = [
    url(r'^$', views.ListPhoto.as_view(), name='photo_list'),
    url(r'^new$', views.PhotoCreate.as_view(), name='photo_new'),
    url(r'^edit/(?P<pk>\d+)$', views.PhotoUpdate.as_view(), name='photo_edit'),
    url(r'^delete/(?P<pk>\d+)$', views.PhotoDelete.as_view(), name='photo_delete'),
]

press_test/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('catalog.urls', namespace='catalog'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.utils.timezone import datetime
from django.db import models


class Photo(models.Model):
    """
    Фотография
    """
    title = models.CharField(verbose_name='Название', max_length=200)
    description = models.TextField(verbose_name='Описание для фотографии', blank=True, null=True)
    image = models.ImageField(verbose_name='Фотография', upload_to='photos/%Y/%m', blank=True)
    data_of_filming = models.DateField(verbose_name='Дата съёмки', default=datetime.now, blank=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Фотография'
        verbose_name_plural = 'Фотографии'

catalog/views.py
import operator
from functools import reduce
from django.db.models import Q
from django.urls import reverse_lazy
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Photo


class ListPhoto(ListView):
    model = Photo
    template_name = 'photo_list.html'
    context_object_name = 'photos'

    def get_queryset(self):
        result = super(ListPhoto, self).get_queryset()

        query = self.request.GET.get('q')
        if query:
            query_list = query.split()
            result = result.filter(
                reduce(operator.and_,
                       (Q(title__icontains=q) for q in query_list)) |
                reduce(operator.and_,
                       (Q(description__icontains=q) for q in query_list)) |
                reduce(operator.and_,
                       (Q(data_of_filming__icontains=q) for q in query_list))
            )
        return result


class PhotoCreate(CreateView):
    model = Photo
    success_url = reverse_lazy('catalog:photo_list')
    fields = ['title', 'description', 'data_of_filming', 'image']


class PhotoUpdate(UpdateView):
    model = Photo
    success_url = reverse_lazy('catalog:photo_list')
    fields = ['title', 'description', 'data_of_filming', 'image']


class PhotoDelete(DeleteView):
    model = Photo
    success_url = reverse_lazy('catalog:photo_list')

catalog/templates/catalog/photo_base.html
<!doctype html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/common.css' %}">
</head>
<body>
    <main>
        {% block content %}
        {% endblock %}
    </main>
</body>
</html>

catalog/templates/catalog/photo_confirm_delete.html
{% extends 'catalog/photo_base.html' %}
{% block content %}

<div class="container">
   <form method="post">{% csrf_token %}
        Вы точно хотети удалить "{{ object }}" ?
        <input type="submit" value="Хочу" />
   </form>


</div>
{% endblock %}

catalog/templates/catalog/photo_form.html
{% extends 'catalog/photo_base.html' %}
{% block content %}

<div class="container">
    <form class="input-group" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="btn btn-default" type="submit" value="ОК" />
    </form>

</div>
{% endblock %}

catalog/templates/catalog/photo_list.html
{% extends 'catalog/photo_base.html' %}
{% load thumbnail %}

    {% block content %}
      <div class="container">
          <div class="row">
              <form class="input-group" action="{% url 'catalog:photo_list' %}" method="get" accept-charset="utf-8">
                    <input type="text" placeholder="Поиск" class="input form-control" name="q">
                    <span class="input-group-btn">
                            <button type="submit" class="btn btn-primary"> <i class="fa fa-search"></i> Поиск</button>
                    </span>
                </form>
          </div>
          <div class="row">
               <a class="btn btn-danger pull-right" href="{% url 'catalog:photo_new' %}">Добавить фотографию</a>
          </div>
          <div class="row">
          {% for photo in photos %}
            <div class="pull-left photo-box">
                <div class="col-md-12">
                    <div class="row">
                        <div class="">
                            <div class="img">
                                <img  src="{% thumbnail photo.image 275x183 crop %}" alt="{{ photo.description }}">
                            </div>
                            <div class="photo-box__info">
                                <ul>
                                    <li><p>Название: {{ photo.title }}</p></li>
                                    <li><p>Описание: {{ photo.description }}</p></li>
                                    <li><p>Дата съёмки: {{ photo.data_of_filming}}</p></li>
                                    <li><a class="btn btn-primary" href="{% url 'catalog:photo_edit' photo.id %}">edit</a></li>
                                    <li><a class="btn btn-primary" href="{% url 'catalog:photo_delete' photo.id %}">delete</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
          {% endfor %}

          </div>
      </div>


    {% endblock %}